# Generated by Django 2.1.2 on 2018-11-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_details', '0040_auto_20181118_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(blank=True, max_length=500)),
                ('rest_menu_slug', models.CharField(blank=True, max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vegetarian_meal', models.BooleanField(blank=True)),
                ('rest_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menurestaurant', to='rest_details.restaurant_details')),
            ],
        ),
    ]
