# Generated by Django 2.1.2 on 2018-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('veg_starter', 'Vegetarian Starter'), ('nonveg_starter', 'Nonveg Starter'), ('veg_maincourse', 'Vegetarian maincourse'), ('nonveg_maincourse', 'Nonveg maincourse'), ('dessert', 'Dessert'), ('Beverages', 'Beverages')], default='Vegetarian maincourse', max_length=50),
        ),
    ]
