# Generated by Django 2.1.2 on 2018-11-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0040_auto_20181118_1534'),
        ('menu', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rest_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartrestaurant', to='rest_details.restaurant_details'),
        ),
    ]
