# Generated by Django 2.1.2 on 2018-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cart_rest_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rest_cart_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
