# Generated by Django 2.1.2 on 2018-11-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20181122_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_name',
            new_name='item_name',
        ),
    ]
