# Generated by Django 2.1.2 on 2018-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='beverages',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='dessert',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
