# Generated by Django 2.1.2 on 2018-11-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20181124_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(max_length=100)),
                ('cart_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total', models.DecimalField(decimal_places=6, max_digits=20)),
                ('f_ord_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkoutrestaurant', to='menu.cart')),
            ],
        ),
    ]
