# Generated by Django 2.1.2 on 2018-11-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='f_ord_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkoutrestaurant', to='reservations.Appointment'),
        ),
    ]
