# Generated by Django 2.1.2 on 2018-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20181125_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
