# Generated by Django 2.1.2 on 2018-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_checkout_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart_price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tax',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
