# Generated by Django 2.1.2 on 2018-11-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20181125_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
