# Generated by Django 2.1.2 on 2018-11-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20181125_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount_due',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='checkout',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
