# Generated by Django 2.1.2 on 2018-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_ordid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
