# Generated by Django 2.1.2 on 2018-11-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_review_review_ordid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
