# Generated by Django 2.1.2 on 2018-11-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0010_auto_20181030_0007'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='table_restaur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablerestaurant', to='rest_details.restaurant_details'),
        ),
    ]
