# Generated by Django 2.1.2 on 2018-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_appointment_tablename_restaur'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tablename_slug',
            field=models.CharField(default='Default Slug', max_length=20),
        ),
    ]
