# Generated by Django 2.1.2 on 2018-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_appointment_tablename_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cust_email',
            field=models.EmailField(default='Anony.chamanee@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Booked', max_length=255),
        ),
    ]
