# Generated by Django 2.1.2 on 2018-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20181108_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mealchoice',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('21:30', '21:30')], default='20:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tablesize',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10')], default=2, max_length=10),
        ),
    ]
