# Generated by Django 2.1.2 on 2018-11-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20181109_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='task',
            new_name='name',
        ),
    ]
