# Generated by Django 2.1.2 on 2018-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0002_restaurant_details_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='gmap_url',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='short_description',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='web_url',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
