# Generated by Django 2.1.2 on 2018-10-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0003_auto_20181028_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_details',
            old_name='date',
            new_name='created',
        ),
    ]
