# Generated by Django 2.1.2 on 2018-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0005_auto_20181028_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='cuisine_type',
            field=models.CharField(choices=[('ITALIANL', 'Italian'), ('MEXICAN', 'Mexican'), ('CHINESE', 'Chinese'), ('MUGHLAI', 'Mughlai'), ('ALL', 'All Cuisine')], default='ALL', max_length=10),
        ),
    ]
