# Generated by Django 2.1.2 on 2018-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0006_auto_20181028_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
