# Generated by Django 2.1.2 on 2018-10-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0007_restaurant_details_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='web_url',
            field=models.CharField(max_length=100),
        ),
    ]
