# Generated by Django 2.1.2 on 2018-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0008_auto_20181029_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='location_image',
            field=models.ImageField(blank=True, upload_to='location_image'),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='logo_image'),
        ),
    ]
