# Generated by Django 2.1.2 on 2018-11-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0010_auto_20181030_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='max_party_size',
            field=models.PositiveIntegerField(blank=True, default=10, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='min_party_size',
            field=models.PositiveIntegerField(blank=True, default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='no_of_res',
            field=models.PositiveIntegerField(blank=True, default=10, max_length=10),
        ),
    ]
