# Generated by Django 2.1.2 on 2018-11-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0011_auto_20181109_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_party_size', models.PositiveIntegerField(blank=True, default=2, max_length=2)),
                ('max_party_size', models.PositiveIntegerField(blank=True, default=10, max_length=10)),
                ('no_of_res', models.PositiveIntegerField(blank=True, default=10, max_length=10)),
                ('restaur_slug', models.CharField(default='Default Slug', max_length=20)),
                ('restaur_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_name', to='rest_details.restaurant_details')),
            ],
        ),
    ]
