# Generated by Django 2.1.2 on 2018-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0014_restaurant_details_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profile_image/'),
        ),
    ]
