# Generated by Django 2.1.2 on 2018-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0016_auto_20181109_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='status',
            field=models.CharField(default='In Process', max_length=20),
        ),
    ]
