# Generated by Django 2.1.2 on 2018-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0017_restaurant_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('accepted', 'accepted')], default='In Process', max_length=20),
        ),
    ]
