# Generated by Django 2.1.2 on 2018-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0018_auto_20181113_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='cuisine_type',
            field=models.CharField(choices=[('ITALIANL', 'Italian'), ('MEXICAN', 'Mexican'), ('CHINESE', 'Chinese'), ('MUGHLAI', 'Mughlai'), ('MULTICUISINE', 'MULTICUISINE')], default='MULTICUISINE', max_length=10),
        ),
    ]
