# Generated by Django 2.1.2 on 2018-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0021_auto_20181115_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='alcohol_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='buffet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='buffet_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='cost_for_two',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
