# Generated by Django 2.1.2 on 2018-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0024_setting_cui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_details',
            name='max_party_size',
        ),
        migrations.RemoveField(
            model_name='restaurant_details',
            name='min_party_size',
        ),
        migrations.RemoveField(
            model_name='restaurant_details',
            name='no_of_res',
        ),
        migrations.RemoveField(
            model_name='restaurant_details',
            name='prof',
        ),
    ]
