# Generated by Django 2.1.2 on 2018-11-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0025_auto_20181115_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='rest_choice',
            field=models.CharField(blank=True, choices=[('Dine-Out Restaurants', 'Dine-Out Restaurants'), ('Pubs and Bars', 'Pubs and Bars'), ('Cafes', 'Cafes'), ('Desserts', 'Desserts')], max_length=50),
        ),
    ]
