# Generated by Django 2.1.2 on 2018-11-15 16:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0026_restaurant_details_rest_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='Pure_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='cost_for_two_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='cui',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ITALIANL', 'Italian'), ('MEXICAN', 'Mexican'), ('CHINESE', 'Chinese'), ('MUGHLAI', 'Mughlai'), ('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Rolls', 'Rolls'), ('Kebabs', 'Kebabs'), ('Momos', 'Momos'), ('Fast Food', 'Fast Food'), ('Dessert', 'Dessert'), ('Ice-Cream', 'Ice-Cream')], max_length=105, null=True),
        ),
    ]
