# Generated by Django 2.1.2 on 2018-11-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0027_auto_20181115_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='cui',
            new_name='Cuisines_You_Offer',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='max_party_size',
            new_name='maximum_party_size',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='min_party_size',
            new_name='minimum_party_size',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='no_of_res',
            new_name='no_of_reservations_per_hour',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cost_for_two',
        ),
    ]
