# Generated by Django 2.1.2 on 2018-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0028_auto_20181115_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='lunch_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
