# Generated by Django 2.1.2 on 2018-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0031_auto_20181115_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_details',
            old_name='location',
            new_name='Area',
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='City',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
