# Generated by Django 2.1.2 on 2018-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0033_auto_20181115_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='Weekday_timings',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant_details',
            name='Weekend_timings',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
