# Generated by Django 2.1.2 on 2018-11-15 17:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0034_auto_20181115_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='Type_of_dining',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Casual Dining', 'Casual Dining'), ('Fine Dining', 'Fine Dining'), ('Bar', 'Bar'), ('Cafe', 'Cafe'), ('Food court', 'Food Court'), ('Quick Bytes', 'Quick Bytes')], max_length=57, null=True),
        ),
    ]
