# Generated by Django 2.1.2 on 2018-11-15 18:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0035_restaurant_details_type_of_dining'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_details',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('CHINESE', 'Chinese'), ('MUGHLAI', 'Mughlai'), ('MULTICUISINE', 'MULTICUISINE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant_details',
            name='Cuisines_You_Offer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('CHINESE', 'Chinese'), ('MUGHLAI', 'Mughlai'), ('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Rolls', 'Rolls'), ('Kebabs', 'Kebabs'), ('Momos', 'Momos'), ('Fast Food', 'Fast Food'), ('Dessert', 'Dessert'), ('Ice-Cream', 'Ice-Cream')], max_length=104, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_details',
            name='Type_of_dining',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Casual Dining', 'Casual Dining'), ('Fine Dining', 'Fine Dining'), ('Bar', 'Bar'), ('Cafe', 'Cafe'), ('Food court', 'Food Court'), ('Quick Bytes', 'Quick Bytes'), ('Bakeries', 'Bakeries')], max_length=66, null=True),
        ),
    ]
