# Generated by Django 2.1.2 on 2018-11-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0036_auto_20181115_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_details',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('ITALIAN', 'ITALIAN'), ('MEXICAN', 'MEXICAN'), ('CHINESE', 'CHINESE'), ('MUGHLAI', 'MUGHLAI'), ('MULTICUISINE', 'MULTICUISINE')], max_length=30),
        ),
    ]
