# Generated by Django 2.1.2 on 2018-11-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0037_auto_20181116_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_details',
            old_name='name',
            new_name='Restaurant_name',
        ),
    ]
