# Generated by Django 2.1.2 on 2018-11-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_details', '0039_auto_20181118_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_details',
            old_name='name',
            new_name='Restaurant_name',
        ),
    ]
